#!/bin/sh
### BEGIN INIT INFO
# Provides:          USB Ethernet Gadget
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Switch to USB Ethernet Gadget when no USB device is connected on Raspberry Pi 0 and 4
### END INIT INFO
# Add to /boot/config.txt
# [pi0w]
# # Enable USB Gadget driver
# dtoverlay=dwc2

# A space separated list of USB Gadget compatible Raspberry Pi board revisions
usbGadgetCompatibleRevisions=" 900092 900093 920093 9000c1 a03111 b03111 c03111 "

DESC="USB Ethernet Gadget"

. /lib/lsb/init-functions

case "$1" in
start)
	# Check if the Raspberry Pi is compatible with USB Gadget mode
	piRevision=`awk '/^Revision\t: / {sub("^1000", "", $3); print $3}' /proc/cpuinfo`
	if ! echo "$usbGadgetCompatibleRevisions" | grep -q " $piRevision "; then
		echo "Raspberry Pi is not compatible with USB Gadget mode"
		exit 0
	fi
	# Raspberry Pi is compatible with USB Gadget mode

	# Check if a USB device is connected
	if lsusb -s 1:2 > /dev/null; then
		log_warning_msg "A USB device is connected"
		exit 0
	fi
	# No USB device is connected

	# Check if dwc2 is enabled
	if ! lsusb -v -s 1:1 2> /dev/null| grep -q " iManufacturer .* dwc2_hsotg$"; then
		log_warning_msg "dwc2 is not enabled"
		exit 1
	fi
	# dwc2 is enabled

	log_daemon_msg "Starting $DESC" "$NAME"

	# Load the kernel modules for dwc2 and Ethernet Gadget
	/sbin/modprobe dwc2
	/sbin/modprobe g_ether

	# Make sure the USB Ethernet Gadget host and device MAC address is always the same between restarts
	if [ ! -f /etc/modprobe.d/g_ether.conf ]; then
		USBGADGETMACADDRESS=`cat /sys/class/net/usb0/address`
		USBGADGETHOSTMACADDRESS=`/bin/dmesg | /bin/sed -n 's/^.*] usb0: HOST MAC \(.*\)$/\1/p'`
		echo "options g_ether host_addr=$USBGADGETHOSTMACADDRESS dev_addr=$USBGADGETMACADDRESS" > /etc/modprobe.d/g_ether.conf
	fi

	# Check if the Ethernet Gadget interface usb0 is created
	if ! /sbin/ifconfig usb0 > /dev/null; then
		log_warning_msg "usb0 device not created"
		exit 1
	fi

	# Successful!
	log_end_msg 0
	exit 0
	;;
stop)
	log_daemon_msg "Stopping $DESC" "$NAME"

	# Unload the kernel modules for dwc2 and Ethernet Gadget
	if ! /sbin/rmmod g_ether 2> /dev/null; then
		log_warning_msg "(not running)"
		exit 1
	fi
	if ! /sbin/rmmod dwc2 2> /dev/null; then
		log_warning_msg "(not running)"
		exit 1
	fi

	# Check if the Ethernet Gadget interface usb0 is removed
	if /sbin/ifconfig usb0 > /dev/null 2>&1; then
		log_end_msg 1
		exit 1
	fi

	# Successful!
	log_end_msg 0
	exit 0
	;;
#restart|force-reload)
#	;;
*)
	#log_failure_msg "Usage: /etc/init.d/usbethernetgadget {start|stop}"
	log_failure_msg "Usage: $0 {start|stop}"
	exit 1
	;;
esac
