#!/bin/sh
### BEGIN INIT INFO
# Provides:          USB ethernet gadget
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Enable USB ethernet gadget
### END INIT INFO

# A space separated list of USB Gadget compatible Raspberry Pi board revisions
usbGadgetCompatibleRevisions=" 900092 900093 920093 9000c1 a03111 b03111 c03111 "

DESC="USB ethernet gadget"

. /lib/lsb/init-functions

case "$1" in
start)
	piRevision=`awk '/^Revision\t: / {sub("^1000", "", $3); print $3}' /proc/cpuinfo`
	if ! echo "$usbGadgetCompatibleRevisions" | grep -q " $piRevision "; then
		echo "Device is not compatible"
		exit 0
	fi

	log_daemon_msg "Starting $DESC" "$NAME"
	# Device is compatible

	# Check if a USB device is connected
	if ! lsusb -v -s 1:1 2> /dev/null| grep -q " iManufacturer .* dwc2_hsotg$"; then
		log_warning_msg "dwc2 not enabled"
		exit 1
	fi

	if lsusb -s 1:2 > /dev/null; then
		log_warning_msg "A USB device is connected"
		exit 1
	fi

	if [ ! -f /etc/modprobe.d/g_ether.conf ]; then
		# Make sure the host and device mac address is allways the same between restarts
		_RANDOMMAC=`hexdump -n4 -e '/1 "%02x:"' /dev/random`
		USBGADGETMACADDRESS="00:${_RANDOMMAC}01"
		USBGADGETHOSTMACADDRESS="00:${_RANDOMMAC}02"
		echo "options g_ether host_addr=$USBGADGETHOSTMACADDRESS dev_addr=$USBGADGETMACADDRESS" > /etc/modprobe.d/g_ether.conf
	fi

	/sbin/modprobe dwc2
	/sbin/modprobe g_ether

	if ! /sbin/ifconfig usb0 > /dev/null; then
		log_warning_msg "usb0 device not created"
		exit 1
	fi
	log_end_msg 0
	exit 0
	;;
stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	/sbin/rmmod g_ether 2> /dev/null || log_warning_msg "(not running)" &&  exit 0
	/sbin/rmmod dwc2 2> /dev/null || log_warning_msg "(not running)" && exit 0
	if /sbin/ifconfig usb0 > /dev/null 2>&1; then
		log_end_msg 1
		exit 1
	fi
	log_end_msg 0
	exit 0
	;;
#restart|force-reload)
#	;;
*)
	log_failure_msg "Usage: /etc/init.d/dhcpcd {start|stop|restart|try-restart|force-reload|status}"
	exit 1
	;;
esac
